### ISSUE TITLE
customise rules，can not use function of attribyfy, how can i fix it?

### ISSUE THREAD

**Issue by dynamicdaniel** [zhcndoc/unocss#1]
/* uno-config.js */
export const rules = [
  [/^cus-ani-(.*)$/, ([, mat]) => {
    const attrsMap = {
      delay: 'animation-delay',
      dir: 'animation-direction',
      direction: 'animation-direction',
      dur: 'animation-duration',
      duration: 'animation-duration',
      fun: 'animation-timing-function',
      count: 'animation-iteration-count',
      name: 'animation-name',
    };
    const [attr, value] = (mat || '').split(':').filter(Boolean);
    console.log(attr, value);
    return value
      ? { [attrsMap[attr]]: value }
      : null;
  }],
];

/* uno.config.js */
import { defineConfig, presetAttributify, presetUno } from 'unocss';
import * as otherConfig from './uno-config.js';

export default defineConfig({
  ...otherConfig,
    // 使用属性方式
    presetAttributify(),
    // 这边提供了tailwind、windicss的兼容，具体可以使用相关vscode插件提示，或查阅官网
    presetUno(),
  ],
  /**
   * 尝试使用tailWind主题配置动画，无效
   * theme配置将来可能问题参考：https://github.com/unocss/unocss/discussions/788
   */
  theme: {
    extend: {
    },
  },
});
![Snipaste_2024-10-17_16-52-51](https://github.com/user-attachments/assets/b7fd0df5-7ee9-46cb-9802-37af7b74846b)
![aaaaaaa](https://github.com/user-attachments/assets/291f76eb-579b-44fb-8654-87877467ef27)

**Comment by ikxin** [comment]
This is just the repository for the Chinese documentation of unocss, only discussing topics related to document translation. For questions about unocss, please visit https://github.com/unocss/unocss.
